/** Web Tailwind tokens (frontend/pages/*.html tailwind-config) — single source for mobile. */
export const WebTokens = {
  primary: "#3525cd",
  primaryContainer: "#4f46e5",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#dad7ff",
  primaryFixed: "#e2dfff",
  primaryFixedDim: "#c3c0ff",
  secondary: "#545f73",
  onSecondary: "#ffffff",
  secondaryContainer: "#d5e0f8",
  onSecondaryContainer: "#586377",
  tertiary: "#7e3000",
  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",
  background: "#fcf8ff",
  onBackground: "#1b1b24",
  surface: "#fcf8ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f5f2ff",
  surfaceContainer: "#f0ecf9",
  surfaceContainerHigh: "#eae6f4",
  surfaceContainerHighest: "#e4e1ee",
  onSurface: "#1b1b24",
  onSurfaceVariant: "#464555",
  surfaceVariant: "#e4e1ee",
  outline: "#777587",
  outlineVariant: "#c7c4d8",
  scoreEmerald: "#059669",
  scoreAmber: "#d97706",
  scoreRed: "#dc2626",
} as const;
